version: 0.2 

phases: 
  install:
    runtime-versions:
        docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - $(aws ecr get-login --no-include-email --region $CI_REGION)
  build: 
    commands: 
    - echo Build started on `date`
    - echo Building backend Docker image...
    - cd backend
    - echo CACHE_HOST=$CACHE_HOST >> .env && echo WCL_PUB_KEY=$WCL_PUB_KEY >> .env
    - docker build -t classicthreat-api .
    - docker tag classicthreat-api:latest $BACKEND_REPO
    - echo Built and tagged backend. Building frontend...
    - cd ../tps-calc-ui
    - echo NODE_ENV=$NODE_ENV >> .env.production && echo VUE_APP_API_URL=$VUE_APP_API_URL >> .env.production
    - docker build -t classicthreat-ui .
    - docker tag classicthreat-ui:latest $UI_REPO
    - echo Front end built.
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing images...
    - docker push $UI_REPO
    - docker push $BACKEND_REPO
    - echo SUCCESS
