version: "3.7"
services:
  app:
    build: backend/.
    ports:
      - 8000:8000
    depends_on:
      - cache
  frontend:
    build: tps-calc-ui/.
    command: npm run serve
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    depends_on:
      - app
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ../data/results:/data