version: 0.2 

phases: 
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - $(aws ecr get-login --no-include-email --region $CI_REGION)
  build: 
    commands: 
    - echo Build started on `date`
    - echo Building backend Docker image...
    - echo CACHE_HOST=$CACHE_HOST >> .env && echo WCL_PUB_KEY=$WCL_PUB_KEY >> .env
    - docker build -t classicthreat-api .
    - docker tag classicthreat-api:latest $BACKEND_REPO
    - echo Built and tagged backend. 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing image...
    - docker push $BACKEND_REPO
    - echo SUCCESS
